### ISSUE TITLE
Track processes waiting for contexts

### ISSUE THREAD

**Issue by NeilLuno** [luno/lu#36]
We have an alert for rink roles that are unassigned. The alert doesn't differentiate between a role that pods are waiting for and a role that is no longer needed. 

For example, consider a `process.ContextRetry` process that runs successfully and then exits. It requested its role initially and then did its business. Since it had the role, other pods would still be sitting waiting for it. Let's say the role is reassigned to each of the other pods, such that every pod has run the `process.ContextRetry` loop. Our alert would then consider the role to be unassigned, despite the fact there there are no longer any processes that need it.

I propose adding a new metric to track processes that are waiting for a context.

```go
func runWithContext(ctx context.Context, getCtx ContextFunc, f lu.ProcessFunc, /* new arg */ name string) error {
        // New bit
        waitingGauge.WithName(name).Set(1)
        defer waitingGauge.WithName(name).Set(0) 
        // End new bit
	runCtx, cancel, err := getCtx(ctx)
	if err != nil {
		return err
	}
	defer cancel()
	return f(runCtx)
}
```

Using that metric, we can exclude roles where there are pods waiting for it.

**Comment by NeilLuno** [comment]
Another option is to put that metric into the `ContextFunc` that's passed in. In that case we could implement it in `lu` userland and not require any changes to this repo.

**Comment by adamhicks** [comment]
I agree that this is an issue, it is important that we can identify roles where we have waiters but no claimer vs when we have no waiters at all.

However, my immediate thought is that it doesn't feel like a `lu` problem and to back that up, you're having to pass in the new parameter which presumably needs to match the embedded role name within `getCtx`

Have you looked at trying to put this into `rink`? Is the metric for the existing alert driven from `lu` or `rink` callbacks?

**Comment by NeilLuno** [comment]
> I agree that this is an issue, it is important that we can identify roles where we have waiters but no claimer vs when we have no waiters at all.
> 
> However, my immediate thought is that it doesn't feel like a `lu` problem and to back that up, you're having to pass in the new parameter which presumably needs to match the embedded role name within `getCtx`
> 
> Have you looked at trying to put this into `rink`? Is the metric for the existing alert driven from `lu` or `rink` callbacks?

Yeah  I might have typed my follow-up before you could see it. I think we can solve this outside lu. Will close.

**Comment by NeilLuno** [comment]
> Is the metric for the existing alert driven from `lu` or `rink` callbacks?

It's using `rink2_cluster_role_bool` from rink. That gauge is 0 in both the scenarios I raised above.
